version: '3.8'
services:
  myapp-db:
    image: postgres:15
    container_name: myapp-db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: jobsdb
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
