version: '3.8'
services:
  myapp-db:
    image: supabase/postgres
    container_name: supabase-db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: supabase_admin
      POSTGRES_DB: supabase
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
